"""Write the OpenAPI document to a committed ``openapi.yaml``.

Run via ``pixi run -e dev generate-openapi``. The output is the same schema
the live app serves at ``/schema/openapi.json``; a drift-guard test keeps the
committed file in sync (see ``tests/test_openapi_spec.py``)."""

import sys
from pathlib import Path

import yaml

from compute_space.web.openapi import build_openapi_schema

_HEADER = "# Generated by `pixi run -e dev generate-openapi` — do not edit by hand.\n"

# .../compute_space/src/compute_space/web/dump_openapi.py -> compute_space/openapi.yaml
_DEFAULT_OUTPUT = Path(__file__).resolve().parents[3] / "openapi.yaml"


def render_openapi_yaml() -> str:
    """Serialize the OpenAPI schema to YAML with the generated-file header."""
    body = yaml.safe_dump(build_openapi_schema(), sort_keys=False, allow_unicode=True)
    return _HEADER + body


def main() -> None:
    output = Path(sys.argv[1]) if len(sys.argv) > 1 else _DEFAULT_OUTPUT
    output.write_text(render_openapi_yaml(), encoding="utf-8")
    print(f"wrote {output}")


if __name__ == "__main__":
    main()
